msmail:
  description: "MS Graph API Credential object."
  type: "object"
  properties:
    tenant_id:
      description: "The tenant ID of the Azure Active Directory."
      type: "string"
      required: true
    client_id:
      description: "The client ID of the Azure Active Directory application."
      type: "string"
      required: true
    client_secret:
      description: "The client secret of the Azure Active Directory application."
      type: "string"
      secret: true
      required: true
    from_email:
      description: "The email address of the sender."
      type: "string"
      required: true
gmail:
  description: "Gmail API Credential object."
  type: "object"
  properties:
    client_id:
      description: "The client ID of the Gmail application."
      type: "string"
      required: true
    client_secret:
      description: "The client secret of the Gmail application."
      type: "string"
      secret: true
      required: true
    refresh_token:
      description: "The client secret of the Gmail application."
      type: "string"
      secret: true
      required: true
